config/routes.rb
Rails.application.routes.draw do
    root "blogs#index"
     resources :blogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true, length: { maximum: 50 }
  validates :content, presence: true, length: { maximum: 140 }
   validates :deadline, presence: true
   scope :sort_deadline, -> { order(deadline: :desc) }
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy] 
#   PER = 25
   
  def index 
   byebug
    if params[:sort_expired] 
#     @blogs = Blog.all.sort_deadline.page(params[:page]).per(PER)   
     @blogs = Blog.page(params[:page]).per(20).order('deadline ASC')
    else
#     @blogs = Blog.order('created_at DESC')  
    @blogs = Blog.page(params[:page]).per(20).order('created_at DESC')
    end
  end 
  

  def new
    @blogs = Blog.new
  end
  
  def create
   
    @blogs = Blog.new(blog_params)
    if @blogs.save

      redirect_to blogs_path
      flash[:success] = 'Blog Created'
    else
      render 'new'
    end
  end
  
 
  def show
   @blogs = Blog.find(params[:id])
  end
  
  def edit
     @blogs = Blog.find(params[:id])
  end
    
  def update
    @blogs = Blog.find(params[:id])
    if @blogs.update(blog_params)
      redirect_to blogs_path, Notice: "You have edited this blog！"
    else
      render 'edit'
    end
  end
  
  def destroy
    @blog.destroy
    redirect_to blogs_path, Notice: "You have deleted the blog!"
  end
  
  private

   def blog_params
     params.require(:blog).permit(:title, :content,  :deadline, :expired_at)
   end
  
  def set_blog
    @blog = Blog.find(params[:id])
  end
  
end  

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_blogs_paths_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blogs, local: true) do |form| %>
  <% if @blogs.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blogs.errors.count %>errors occurred.</h2>
      <ul>

      <% @blogs.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group form-group">
      <div class="controls">
        <%= form.label :"TITLE" %>
        <%= form.text_field :title, id: :blog_title, class:"form-control"%>
      </div>
    </div>

    <div class="control-group form-group">
      <div class="controls">
        <%= form.label :"CONTENT %>
        <%= form.text_area :content, id: :blog_content, class:"form-control" %>
      </div>
    </div>
<div class="control-group form-group">
      <div class="controls">
        <%= form.label :"EXP" %>
        <%= form.date_field :deadline, id: :blog_deadline, class:"form-control" %>
      </div>
    </div>
 <div class="actions">
    <%= form.submit class:"btn btn-primary", id:"sendMessageButton"%>
  </div>
<% end %>

<%= link_to "Return to List of duffs screen", blogs_path %>
<%= t('blog.index') %>

app/views/blogs/destroy.html.erb
<%= form_with(model: @blogs, local: true) do |form| %>
<div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <h2>Create a new blog</h2>

 
  <%= form.submit %>
<% end %>

app/views/blogs/edit.html.erb
<%= form_with(model: @blogs, local: true) do |form| %>
  <% if @blogs.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blogs.errors.count %>errors occurred.</h2>
      <ul>

      <% @blogs.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 div class="control-group form-group">
      <div class="controls">
        <%= form.label :"Title" %>
        <%= form.text_field :title, id: :blog_title, class:"form-control"%>
      </div>
    </div>

    <div class="control-group form-group">
      <div class="controls">
        <%= form.label :"Content" %>
        <%= form.text_area :content, id: :blog_content, class:"form-control" %>
      </div>
    </div>

    <div class="control-group form-group">
      <div class="controls">
        <%= form.label :"EXP" %>
        <%= form.date_field :deadline, id: :blog_deadline, class:"form-control" %>
      </div>
    </div>
 <div class="actions">
    <%= form.submit class:"btn btn-primary", id:"sendMessageButton"%>
  </div>
<% end %>

<%= link_to "Return to List of duffs screen", blogs_path %>
<%= t('blog.index') %>

app/views/blogs/index.html.erb
<h1>List of Posts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Contents</th></th>
  </tr>


<%= link_to "Expiration", blogs_path(sort_expired: "true"), class: 'btn btn-outline-warning btn-sm' %>
<% byebug %>
<% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.title %></td>
    <td><%= blog.content %></td>
    <td><%= blog.deadline %></td>
   <td><%= link_to 'Check the details', blog_path(blog.id) %></td>
   
  
    <td><%= link_to link_to "Edit this duff", edit_blog_path(blog.id) %></td>
    <td><%= link_to link_to 'Delete this duff', blog_path(blog.id), method: :delete ,data: {confirm: 'Are you sure?'} %></td>
    
  </tr>
<% end %>
 
</table>

<br>
<%= link_to 'New Post', new_blog_path %>
<%= t('blog.index') %>

app/views/blogs/new.html.erb
<%= form_with(model: @blogs, local: true) do |form| %>
  <% if @blogs.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blogs.errors.count %>errors occurred.</h2>
      <ul>

      <% @blogs.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="control-group form-group">
      <div class="controls">
        <%= form.label :"Title" %>
        <%= form.text_field :title, id: :blog_title, class:"form-control"%>
      </div>
    </div>

    <div class="control-group form-group">
      <div class="controls">
        <%= form.label :"Content" %>
        <%= form.text_area :content, id: :blog_content, class:"form-control" %>
      </div>
    </div>

    <div class="control-group form-group">
      <div class="controls">
        <%= form.label :"EXP" %>
        <%= form.date_field :deadline, id: :blog_deadline, class:"form-control" %>
      </div>
    </div>
 <div class="actions">
    <%= form.submit class:"btn btn-primary", id:"sendMessageButton"%>
  </div>
<% end %>

<%= link_to "Return to List of duffs screen", blogs_path %>
<%= t('blog.index') %>

app/views/blogs/show.html.erb
<h1>Duff Detail Screen </h1>

<table  class="new_table">

    <tr><th><%= t('view.title') %></th>
      <td><%= @blog.title %></td></tr>
    <tr><th><%= t('view.content') %></th>
      <td><%= @blog.content %></td></tr>
    <tr><th><%= t('view.created_at') %></th>
      <td><%= @blog.created_at.strftime("%Y-%m-%d") %></td></tr>
    <tr><th><%= t('view.expired_at') %></th>
      <td><%= @blog.expired_at.strftime("%Y-%m-%d") %></td></tr>
      
  </table>

<%= t('blog.index') %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Docs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>